[package]
name = "arch_desc"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
core = { path = "../core" }
utility = { path = "../utility" }
once_cell = "1.17.1"
num-traits = "0.2.15"
