mod architecture;
pub use architecture::*;
mod register;
pub use register::*;
mod instruction;
pub use instruction::*;
mod primitives;
pub use primitives::*;
mod register_file;
pub use register_file::*;
pub mod ir;
