[package]
name = "machineinstr"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[[bin]]
name = "disassemble"
path = "disassemble.rs"

[dependencies]
num-traits = "0.2.15"
elf = "0.7.1"
once_cell = "1.17.0"
